spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.25.168:3306/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
    mybatis-plus:
      global-config:
        db-config:
          id-type: auto
